ARG ALERTMANAGER_VERSION
FROM prom/alertmanager:${ALERTMANAGER_VERSION}

COPY conf /etc/alertmanager/

ENTRYPOINT  [ "/etc/alertmanager/docker-entrypoint.sh" ]
CMD        [ "--config.file=/etc/alertmanager/alertmanager.yml", \
             "--storage.path=/alertmanager" ]
